[package]
name = "iyesmesh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive", "env", "unicode", "wrap_help"] }
iyes_mesh = { path = "../../" }
obj-rs = { version = "0.7.4", optional = true }

[features]
default = ["obj"]
obj = ["dep:obj-rs"]
